import { PhaseCard } from '../engine/types';

export const PHASE_CARDS: PhaseCard[] = [
  {
    id: 'pickLock',
    name: 'PICK LOCK',
    type: 'phase',
    requirement: { kind: 'xOfAKind', count: 2 },
    momentumDice: [4, 4],
  },
  {
    id: 'retinaScanner',
    name: 'RETINA SCANNER',
    type: 'phase',
    requirement: { kind: 'sum', op: 'eq', value: 1, minDice: 1 },
    momentumDice: [4],
  },
  {
    id: 'hackTurret',
    name: 'HACK A TURRET',
    type: 'phase',
    requirement: { kind: 'sum', op: 'eq', value: 4, minDice: 1 },
    momentumDice: [6],
  },
  {
    id: 'disableCams',
    name: 'DISABLE CAMS',
    type: 'phase',
    requirement: { kind: 'sum', op: 'eq', value: 7 },
    momentumDice: [6, 6],
    onPlayEffect: { id: 'rerollAll', text: 'Reroll all pool dice' },
  },
  {
    id: 'bodyguard',
    name: 'BODYGUARD',
    type: 'phase',
    requirement: { kind: 'sum', op: 'gte', value: 12 },
    momentumDice: [6, 6],
    onPlayEffect: { id: 'setDieToMax', text: 'Set one die to its max', requiresTarget: 'die' },
  },
  {
    id: 'petGuardDog',
    name: 'PET GUARD DOG',
    type: 'phase',
    requirement: { kind: 'sum', op: 'gte', value: 15 },
    momentumDice: [4, 6, 6],
    onPlayEffect: { id: 'rerollAll', text: 'Reroll all pool dice' },
  },
  {
    id: 'lasers',
    name: 'LASERS!',
    type: 'phase',
    requirement: { kind: 'sum', op: 'gte', value: 15 },
    momentumDice: [20],
  },
  {
    id: 'motionSensors',
    name: 'MOTION SENSORS',
    type: 'phase',
    requirement: { kind: 'sum', op: 'lt', value: 6, minDice: 2 },
    momentumDice: [6, 6],
  },
  {
    id: 'pressurePlates',
    name: 'PRESSURE PLATES',
    type: 'phase',
    requirement: { kind: 'sum', op: 'lt', value: 7, minDice: 3 },
    momentumDice: [4, 4, 4],
  },
  {
    id: 'jumpFence',
    name: 'JUMP THE FENCE',
    type: 'phase',
    requirement: { kind: 'xOfAKind', count: 2 },
    momentumDice: [4, 4],
  },
  {
    id: 'electricFence',
    name: 'ELECTRIC FENCE',
    type: 'phase',
    requirement: { kind: 'straight', length: 4 },
    momentumDice: [4, 4, 4],
  },
  {
    id: 'elevatorShaft',
    name: 'ELEVATOR SHAFT',
    type: 'phase',
    requirement: { kind: 'straight', length: 3 },
    momentumDice: [6, 6],
    onPlayEffect: { id: 'removeOnes', text: 'Remove all dice showing 1' },
  },
  {
    id: 'highjackTank',
    name: 'HIGHJACK A TANK',
    type: 'phase',
    requirement: { kind: 'xOfAKind', count: 3 },
    momentumDice: [20],
  },
  {
    id: 'nightVision',
    name: 'NIGHT VISION',
    type: 'phase',
    requirement: { kind: 'sum', op: 'gte', value: 8 },
    momentumDice: [4, 6],
    onPlayEffect: { id: 'setTwoDiceToOne', text: 'Set 2 dice to 1', requiresTarget: 'dice' },
  },
  {
    id: 'skylightRepel',
    name: 'SKYLIGHT REPEL',
    type: 'phase',
    requirement: { kind: 'sum', op: 'gte', value: 12 },
    momentumDice: [6, 6],
    onPlayEffect: { id: 'rerollLowest', text: 'Reroll the lowest die' },
  },
  {
    id: 'airDuct',
    name: 'AIR DUCT',
    type: 'phase',
    requirement: { kind: 'sum', op: 'lt', value: 3 },
    momentumDice: [6],
    onPlayEffect: { id: 'rerollHighest', text: 'Reroll the highest die' },
  },
  {
    id: 'netsec',
    name: 'NETSEC',
    type: 'phase',
    requirement: { kind: 'sum', op: 'eq', value: 10 },
    momentumDice: [6, 4],
  },
  {
    id: 'blackout',
    name: 'BLACKOUT',
    type: 'phase',
    requirement: { kind: 'sum', op: 'eq', value: 5 },
    momentumDice: [4],
    onPlayEffect: { id: 'rerollAll', text: 'Reroll all pool dice' },
  },
  {
    id: 'smokeBomb',
    name: 'SMOKE BOMB',
    type: 'phase',
    requirement: { kind: 'sum', op: 'lt', value: 5, minDice: 1 },
    momentumDice: [4],
    onPlayEffect: { id: 'removeOnes', text: 'Remove all dice showing 1' },
  },
  {
    id: 'sleightOfHand',
    name: 'SLEIGHT OF HAND',
    type: 'phase',
    requirement: { kind: 'xOfAKind', count: 2 },
    momentumDice: [6],
    onPlayEffect: { id: 'setDieToMax', text: 'Set one die to its max', requiresTarget: 'die' },
  },
  {
    id: 'graplingHook',
    name: 'GRAPPLING HOOK',
    type: 'phase',
    requirement: { kind: 'sum', op: 'gte', value: 9 },
    momentumDice: [6, 4],
  },
  {
    id: 'bribeGuard',
    name: 'BRIBE THE GUARD',
    type: 'phase',
    requirement: { kind: 'sum', op: 'gte', value: 10 },
    momentumDice: [6, 6],
    onPlayEffect: { id: 'setDieToMax', text: 'Set one die to its max', requiresTarget: 'die' },
  },

  // --- Parity / max-face phase cards ----------------------------------------
  // Lean on the new evens / odds / maxes requirement kinds. Names skew
  // cyberpunk-systems so the requirements read thematically.
  {
    id: 'fiberSplice',
    name: 'FIBER SPLICE',
    type: 'phase',
    requirement: { kind: 'evens', count: 2 },
    momentumDice: [6, 4],
  },
  {
    id: 'parityHack',
    name: 'PARITY HACK',
    type: 'phase',
    requirement: { kind: 'evens', count: 3 },
    momentumDice: [6, 6],
    onPlayEffect: { id: 'rerollLowest', text: 'Reroll the lowest die' },
  },
  {
    id: 'oddRouting',
    name: 'ODD ROUTING',
    type: 'phase',
    requirement: { kind: 'odds', count: 2 },
    momentumDice: [6, 4],
  },
  {
    id: 'primeChannel',
    name: 'PRIME CHANNEL',
    type: 'phase',
    requirement: { kind: 'odds', count: 3 },
    momentumDice: [6, 6],
    onPlayEffect: { id: 'rerollHighest', text: 'Reroll the highest die' },
  },
  {
    id: 'maxOverclock',
    name: 'MAX OVERCLOCK',
    type: 'phase',
    requirement: { kind: 'maxes', count: 2 },
    momentumDice: [8, 6],
    onPlayEffect: { id: 'setDieToMax', text: 'Set one die to its max', requiresTarget: 'die' },
  },
  {
    id: 'criticalBurn',
    name: 'CRITICAL BURN',
    type: 'phase',
    requirement: { kind: 'maxes', count: 1 },
    momentumDice: [8],
  },
];

export function getPhaseCard(id: string): PhaseCard | undefined {
  return PHASE_CARDS.find((c) => c.id === id);
}
